//
//  Graphics.h
//  Marcus
//
//  Created by Marcus Lewis on 2/5/16.
//  Copyright (c) 2016 SMGMobile. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface Graphics : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* bookTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* quoteTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* settingsTargets;

// Drawing Methods
+ (void)drawBook: (UIColor*) color;
+ (void)drawQuote: (UIColor*) color;
+ (void)drawSettings: (UIColor*) color;

// Generated Images
+ (UIImage*)imageOfBook;
+ (UIImage*)imageOfBookWithColor: (UIColor*) color;
+ (UIImage*)imageOfQuote;
+ (UIImage*)imageOfQuoteWithColor: (UIColor*) color;
+ (UIImage*)imageOfSettings;
+ (UIImage*)imageOfSettingsWithColor: (UIColor*) color;

@end